# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
# ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28

# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred
# divisors?


def divisors(x: int, primes: list[int]):
	divisors = 1
	mx = int(x**0.5) + 1
	for p in primes:
		if p > mx:
			break
		if x == 1:
			break
		if x % p != 0:
			continue
		count = 0
		while x % p == 0:
			count += 1
			x = x // p
		divisors *= count + 1
	if x != 1:
		divisors *= 2
		primes.append(x)
	return divisors


def main():
	i = 2
	primes = [2, 3, 5, 7]
	while True:
		i += 1
		x = (i * (i + 1)) // 2
		if divisors(x, primes) > 500:
			return x
