# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1,2,3,5,8,13,34,55,89
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.


def main(mx: int = 4_000_000):
	s = 2
	a, b = 1, 2
	while True:
		a, b = b, a + b
		a, b = b, a + b
		a, b = b, a + b
		if b > mx:
			break
		s += b
	return s
